on:
  workflow_dispatch:
  push:
    paths:
      - '**.java'
  pull_request:
    paths:
      - '**.java'

name: build

jobs:
  build:
    name: Build and test on Linux
    runs-on: ubuntu-latest
    env:
      PZ_VERSION: 42.14.1
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 25
#      # Configure GPG key
#      # as described https://github.com/crazy-max/ghaction-import-gpg
#      - name: Import GPG key
#        id: import_gpg
#        uses: crazy-max/ghaction-import-gpg@v5
#        with:
#          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
#          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Download Zomboid classes from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          mkdir -p lib
          aws s3 cp "s3://${{ secrets.S3_BUCKET }}/zomboid-${{ env.PZ_VERSION }}.zip" lib/zomboid-${{ env.PZ_VERSION }}.zip
          unzip lib/zomboid-${{ env.PZ_VERSION }}.zip -d lib/zomboid
      - name: Create local.properties
        run: |
          echo "gameDir=${{ github.workspace }}/lib/zomboid" > local.properties
      - name: Test
        run: |
          ./gradlew test
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ runner.os }}
          path: ./**/build/reports/tests/
#
#      - name: Upload Artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: Package
#          path: |
#            build/distributions/*.tar
#            build/distributions/*.zip
